=== Election-Tech-Initiative/electionguard/data/1.0.0-preview-1/schema/submitted_ballot.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://electionguard.vote/schemas/1.0.0-preview-2/submitted-ballot",
  "title": "Submitted Ballot",
  "description": "A `SubmittedBallot` represents a ballot that is submitted for inclusion in election results. A submitted ballot is or is about to be either cast or spoiled. The state supports the `BallotBoxState.UNKNOWN` enumeration to indicate that this object is mutable and has not yet been explicitly assigned a specific state. Note, additionally, this ballot includes all proofs but no nonces.",
  "type": "object",
  "required": [
    "object_id",
    "style_id",
    "manifest_hash",
    "code_seed",
    "contests",
    "code",
    "timestamp",
    "crypto_hash",
    "nonce",
    "state"
  ],
  "definitions": {
    "SequenceOrder": {
      "title": "Sequence Order",
      "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
      "type": "integer",
      "minimum": 1
    },
    "ElementModP": {
      "title": "ElementModP",
      "description": "An element of the larger `mod p` space, i.e., in [0, P), where P is a 4096-bit prime.",
      "type": "string"
    },
    "ElementModQ": {
      "title": "ElementModQ",
      "description": "An element of the smaller `mod q` space, i.e., in [0, Q), where Q is a 256-bit prime.",
      "type": "string"
    },
    "BallotBoxState": {
      "title": "BallotBox State",
      "description": "Enumeration used when marking a ballot as cast or spoiled",
      "type": "integer",
      "enum": [1, 2, 999],
      "default": 999
    },
    "ElGamalCiphertext": {
      "title": "ElGamal Ciphertext",
      "description": "An exponential ElGamal ciphertext",
      "type": "object",
      "required": ["pad", "data"],
      "properties": {
        "pad": {
          "title": "Pad",
          "description": "pad or alpha",
          "$ref": "#/definitions/ElementModQ"
        },
        "data": {
          "title": "Data",
          "description": "encrypted data or beta",
          "$ref": "#/definitions/ElementModQ"
        }
      }
    },
    "HashedElGamalCiphertext": {
      "title": "Hashed ElGamal Ciphertext",
      "description": "A hashed version of ElGamal Ciphertext with less size restrictions.",
      "type": "object",
      "required": ["pad", "data", "mac"],
      "properties": {
        "pad": {
          "title": "Pad",
          "description": "pad or alpha",
          "$ref": "#/definitions/ElementModP"
        },
        "data": {
          "title": "Data",
          "description": "encrypted data or beta",
          "type": "string"
        },
        "mac": {
          "title": "MAC",
          "description": "message authentication code for hmac",
          "type": "string"
        }
      }
    },
    "ProofUsage": {
      "title": "Proof Usage",
      "description": "Usage case for proof",
      "type": "string",
      "enum": [
        "Unknown",
        "Prove knowledge of secret value",
        "Prove value within selection's limit",
        "Prove selection's value (0 or 1)"
      ],
      "default": "Unknown"
    },
    "ConstantChaumPedersenProof": {
      "title": "Constant Chaum Pedersen Proof",
      "description": "Usage case for proof",
      "type": "object",
      "required": ["pad", "data", "challenge", "response", "constant", "usage"],
      "properties": {
        "pad": {
          "title": "Pad",
          "description": "a in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "data": {
          "title": "Data",
          "description": "b in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "challenge": {
          "title": "Challenge",
          "description": "c in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "response": {
          "title": "Response",
          "description": "v in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "constant": {
          "title": "Constant",
          "description": "constant value",
          "type": "integer"
        },
        "usage": {
          "title": "Usage",
          "description": "A description of how to use this proof",
          "$ref": "#/definitions/ProofUsage",
          "default": "Prove value within selection's limit"
        }
      }
    },
    "DisjunctiveChaumPedersenProof": {
      "title": "Disjunctive Chaum Pedersen Proof",
      "description": "Representation of disjunctive Chaum Pederson proof",
      "type": "object",
      "required": [
        "proof_zero_pad",
        "proof_zero_data",
        "proof_one_pad",
        "proof_one_data",
        "proof_zero_challenge",
        "proof_one_challenge",
        "challenge",
        "proof_zero_response",
        "proof_one_response",
        "usage"
      ],
      "properties": {
        "proof_zero_pad": {
          "title": "Proof Zero Pad",
          "description": "a0 in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "proof_zero_data": {
          "title": "Proof Zero Data",
          "description": "b0 in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "proof_one_pad": {
          "title": "Proof One Pad",
          "description": "a1 in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "proof_one_data": {
          "title": "Proof One Data",
          "description": "b1 in the spec",
          "$ref": "#/definitions/ElementModP"
        },
        "proof_zero_challenge": {
          "title": "Proof Zero Challenge",
          "description": "c0 in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "proof_one_challenge": {
          "title": "Proof One Challenge",
          "description": "c1 in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "challenge": {
          "title": "Challenge",
          "description": "c in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "proof_zero_response": {
          "title": "Proof Zero Response",
          "description": "proof_zero_response in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "proof_one_response": {
          "title": "Proof One Response",
          "description": "proof_one_response in the spec",
          "$ref": "#/definitions/ElementModQ"
        },
        "usage": {
          "title": "Usage",
          "description": "A description of how to use this proof",
          "$ref": "#/definitions/ProofUsage",
          "default": "Prove selection's value (0 or 1)"
        }
      }
    },
    "CiphertextBallotSelection": {
      "title": "Ciphertext Ballot Selection",
      "description": "A CiphertextBallotSelection represents an individual encrypted selection on a ballot.",
      "type": "object",
      "required": [
        "object_id",
        "sequence_order",
        "description_hash",
        "ciphertext",
        "crypto_hash",
        "is_placeholder_selection",
        "nonce",
        "proof"
      ],
      "properties": {
        "object_id": {
          "title": "Object_id",
          "type": "string"
        },
        "sequence_order": {
          "title": "Sequence Order",
          "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
          "$ref": "#/definitions/SequenceOrder"
        },
        "description_hash": {
          "title": "Description_hash",
          "description": "The SelectionDescription hash",
          "$ref": "#/definitions/ElementModQ"
        },
        "ciphertext": {
          "title": "Ciphertext",
          "description": "The encrypted representation of the vote field",
          "$ref": "#/definitions/ElGamalCiphertext"
        },
        "crypto_hash": {
          "title": "Crypto Hash",
          "description": "The hash of the encrypted values",
          "$ref": "#/definitions/ElementModQ"
        },
        "is_placeholder_selection": {
          "title": "Is Placeholder Selection",
          "description": "Determines if this is a placeholder selection",
          "type": "boolean",
          "default": false
        },
        "nonce": {
          "title": "Nonce",
          "description": "The nonce used to generate the encryption. Sensitive & should be treated as a secret",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/ElementModQ" }
          ],
          "default": null
        },
        "proof": {
          "title": "Proof",
          "description": "The proof that demonstrates the selection is an encryption of 0 or 1, and was encrypted using the `nonce`",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/DisjunctiveChaumPedersenProof" }
          ],
          "default": null
        }
      }
    },
    "CiphertextBallotContest": {
      "title": "Ciphertext Ballot Contest",
      "description": "A CiphertextBallotContest represents the selections made by a voter for a specific ContestDescription.",
      "type": "object",
      "required": [
        "object_id",
        "sequence_order",
        "description_hash",
        "ballot_selections",
        "ciphertext_accumulation",
        "crypto_hash",
        "nonce",
        "proof",
        "extended_data"
      ],
      "properties": {
        "object_id": {
          "title": "Object Id",
          "type": "string"
        },
        "sequence_order": {
          "title": "Sequence Order",
          "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
          "$ref": "#/definitions/SequenceOrder"
        },
        "description_hash": {
          "title": "Description Hash",
          "description": "Hash from contestDescription",
          "$ref": "#/definitions/ElementModQ"
        },
        "ballot_selections": {
          "title": "Ballot_selections",
          "type": "array",
          "default": [],
          "items": {
            "title": "Items",
            "$ref": "#/definitions/CiphertextBallotSelection"
          }
        },
        "ciphertext_accumulation": {
          "title": "Ciphertext Accumulation",
          "description": "The encrypted representation of all of the vote fields (the contest total)",
          "$ref": "#/definitions/ElGamalCiphertext"
        },
        "crypto_hash": {
          "title": "Crypto Hash",
          "description": "Hash of the encrypted values",
          "$ref": "#/definitions/ElementModQ"
        },
        "nonce": {
          "title": "Nonce",
          "description": "The nonce used to generate the encryption. Sensitive & should be treated as a secret",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/ElementModQ" }
          ],
          "default": null
        },
        "proof": {
          "title": "Proof",
          "description": "The proof demonstrates the sum of the selections does not exceed the maximum available selections for the contest, and that the proof was generated with the nonce",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/ElGamalCiphertext" }
          ],
          "default": null
        },
        "extended_data": {
          "title": "Extended Data",
          "description": "Encrypted representation of the extended_data field",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/HashedElGamalCiphertext" }
          ],
          "default": null
        }
      }
    }
  },
  "properties": {
    "object_id": {
      "title": "Object Id",
      "type": "string"
    },
    "style_id": {
      "title": "Style Id",
      "description": "The `object_id` of the `BallotStyle` in the `Election` Manifest",
      "type": "string"
    },
    "manifest_hash": {
      "title": "Manifest Hash",
      "description": "Hash of the election manifest",
      "$ref": "#/definitions/ElementModQ"
    },
    "code_seed": {
      "title": "Code_seed",
      "description": "Seed for ballot code",
      "$ref": "#/definitions/ElementModQ"
    },
    "contests": {
      "title": "Contests",
      "description": "List of contests for this ballot",
      "type": "array",
      "default": [],
      "items": {
        "title": "Items",
        "$ref": "#/definitions/CiphertextBallotContest"
      }
    },
    "code": {
      "title": "Code",
      "description": "Unique ballot code for this ballot",
      "$ref": "#/definitions/ElementModQ"
    },
    "timestamp": {
      "title": "Timestamp",
      "description": "Timestamp at which the ballot encryption is generated in tick",
      "type": "integer"
    },
    "crypto_hash": {
      "title": "Crypto Hash",
      "description": "The hash of the encrypted ballot representation",
      "$ref": "#/definitions/ElementModQ"
    },
    "nonce": {
      "title": "Nonce",
      "description": "The nonce used to encrypt this ballot. Sensitive & should be treated as a secret",
      "oneOf": [{ "type": "null" }, { "$ref": "#/definitions/ElementModQ" }],
      "default": null
    },
    "state": {
      "title": "State",
      "description": "Submitted state of the ballot",
      "$ref": "#/definitions/BallotBoxState"
    }
  }
}

=== Election-Tech-Initiative/electionguard/data/1.0.0-preview-1/sample/hamilton-general/election_record/submitted_ballots/submitted_ballot_03a29d15-667c-4ac8-afd7-549f19b8e4eb.json
{
  "object_id": "03a29d15-667c-4ac8-afd7-549f19b8e4eb",
  "style_id": "jefferson-county-ballot-style",
  "manifest_hash": "6208",
  "code_seed": "0936",
  "contests": [
    {
      "object_id": "justice-supreme-court",
      "sequence_order": 0,
      "description_hash": "8902",
      "ballot_selections": [
        {
          "object_id": "john-adams-selection",
          "sequence_order": 0,
          "description_hash": "98A7",
          "ciphertext": {
            "pad": "6EBC02BE82146B2A",
            "data": "0BDCB68B757376E2"
          },
          "crypto_hash": "220B",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "132FCA1366AF66A3",
            "proof_zero_data": "740C8D5614BC4BA8",
            "proof_one_pad": "4D155FF770CC3123",
            "proof_one_data": "754A53E339B0FE53",
            "proof_zero_challenge": "5C8F",
            "proof_one_challenge": "9843",
            "challenge": "F4D2",
            "proof_zero_response": "4450",
            "proof_one_response": "C95F",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "benjamin-franklin-selection",
          "sequence_order": 1,
          "description_hash": "5FDA",
          "ciphertext": {
            "pad": "8C2802307D378564",
            "data": "199FBCD7FA5507FC"
          },
          "crypto_hash": "5C1A",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "E9CBB3A7AF559998",
            "proof_zero_data": "B2DC1F6CD97FE4EC",
            "proof_one_pad": "C98A2FEF0F45DE1E",
            "proof_one_data": "42276B0A778F1F9C",
            "proof_zero_challenge": "F8E3",
            "proof_one_challenge": "01A4",
            "challenge": "FA87",
            "proof_zero_response": "A90E",
            "proof_one_response": "B343",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "john-hancock-selection",
          "sequence_order": 2,
          "description_hash": "3316",
          "ciphertext": {
            "pad": "C5DEA1F26028D9E0",
            "data": "AAD1AD668DC5A9C7"
          },
          "crypto_hash": "E40C",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "10712B223D075437",
            "proof_zero_data": "C22CF0937E3668",
            "proof_one_pad": "87F9E452AD78563C",
            "proof_one_data": "256C1E293B21E526",
            "proof_zero_challenge": "8718",
            "proof_one_challenge": "CC71",
            "challenge": "5398",
            "proof_zero_response": "0E8A",
            "proof_one_response": "DD4A",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "write-in-selection",
          "sequence_order": 3,
          "description_hash": "3086",
          "ciphertext": {
            "pad": "B89D074B9802A214",
            "data": "8D28545CB483D47B"
          },
          "crypto_hash": "7828",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "17FE4F19F02EACD9",
            "proof_zero_data": "E34E6FE2D8573C4E",
            "proof_one_pad": "C7C2B4EA510BCA2D",
            "proof_one_data": "1C534DDD476CD86F",
            "proof_zero_challenge": "8128",
            "proof_one_challenge": "19A9",
            "challenge": "9AD1",
            "proof_zero_response": "67C1",
            "proof_one_response": "2335",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "justice-supreme-court-4-placeholder",
          "sequence_order": 4,
          "description_hash": "2E68",
          "ciphertext": {
            "pad": "3EAB29D0C2CEF796",
            "data": "981491F1B61AFDDA"
          },
          "crypto_hash": "3931",
          "is_placeholder_selection": true,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "84523BF14F9F78F3",
            "proof_zero_data": "9341AD83E8468146",
            "proof_one_pad": "0314DA920952FD72",
            "proof_one_data": "125FD94BA6B8AB73",
            "proof_zero_challenge": "B6BE",
            "proof_one_challenge": "B426",
            "challenge": "6AF3",
            "proof_zero_response": "D786",
            "proof_one_response": "4755",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "justice-supreme-court-5-placeholder",
          "sequence_order": 5,
          "description_hash": "5C58",
          "ciphertext": {
            "pad": "67318E98373ADC94",
            "data": "FD7C0441C1636025"
          },
          "crypto_hash": "9F38",
          "is_placeholder_selection": true,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "A5F802D7B989090F",
            "proof_zero_data": "5A945AFFAF7FDF57",
            "proof_one_pad": "0CCCA905A5A4D2EA",
            "proof_one_data": "F4F723F68DF884D4",
            "proof_zero_challenge": "7BC1",
            "proof_one_challenge": "469C",
            "challenge": "C25D",
            "proof_zero_response": "025C",
            "proof_one_response": "4425",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        }
      ],
      "ciphertext_accumulation": {
        "pad": "EB3F8FDB1445CCC7",
        "data": "F1765D313BF78B07"
      },
      "crypto_hash": "FA2E",
      "nonce": null,
      "proof": {
        "pad": "D882F3E4A79873DF",
        "data": "42CBD3E9C9383B8D",
        "challenge": "0861",
        "response": "457D",
        "constant": 2,
        "usage": "Prove value within selection's limit"
      },
      "extended_data": null
    }
  ],
  "code": "A533",
  "timestamp": 1651598676,
  "crypto_hash": "45EF",
  "nonce": null,
  "state": 2
}

=== Election-Tech-Initiative/electionguard/data/1.0.0-preview-1/sample/hamilton-general/election_record/submitted_ballots/submitted_ballot_1048ce32-f1b1-4b05-b7fb-8c615ac842ee.json
{
  "object_id": "1048ce32-f1b1-4b05-b7fb-8c615ac842ee",
  "style_id": "jefferson-county-ballot-style",
  "manifest_hash": "6208",
  "code_seed": "8BE2",
  "contests": [
    {
      "object_id": "justice-supreme-court",
      "sequence_order": 0,
      "description_hash": "8902",
      "ballot_selections": [
        {
          "object_id": "john-adams-selection",
          "sequence_order": 0,
          "description_hash": "98A7",
          "ciphertext": {
            "pad": "B94F3DE3DDE18F1D",
            "data": "BBD0B59410A6876C"
          },
          "crypto_hash": "0B33",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "331E03C2048AF7C1",
            "proof_zero_data": "B369CEB306A471F2",
            "proof_one_pad": "662E0F37229D4241",
            "proof_one_data": "40CFB58229BE4A05",
            "proof_zero_challenge": "F277",
            "proof_one_challenge": "CAEA",
            "challenge": "BD70",
            "proof_zero_response": "51AD",
            "proof_one_response": "59B9",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "benjamin-franklin-selection",
          "sequence_order": 1,
          "description_hash": "5FDA",
          "ciphertext": {
            "pad": "D0CE21ABE262B13E",
            "data": "A1A237C63F3BF72B"
          },
          "crypto_hash": "9F35",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "1938F475F21239FB",
            "proof_zero_data": "137D77B7491570D3",
            "proof_one_pad": "9B8F4881D4A62A1D",
            "proof_one_data": "E459AC90306CDAE6",
            "proof_zero_challenge": "608D",
            "proof_one_challenge": "E8F2",
            "challenge": "498E",
            "proof_zero_response": "1EB3",
            "proof_one_response": "C47D",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "john-hancock-selection",
          "sequence_order": 2,
          "description_hash": "3316",
          "ciphertext": {
            "pad": "595F4A1BD4921F22",
            "data": "A061D0C788E0AE53"
          },
          "crypto_hash": "ECB4",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "F23ECAE9907D93D5",
            "proof_zero_data": "2BAE76E44AC052E4",
            "proof_one_pad": "0145FD0CE34DED9C",
            "proof_one_data": "3F3BCE31DF06D1DE",
            "proof_zero_challenge": "F3BE",
            "proof_one_challenge": "3312",
            "challenge": "26DF",
            "proof_zero_response": "413D",
            "proof_one_response": "205F",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "write-in-selection",
          "sequence_order": 3,
          "description_hash": "3086",
          "ciphertext": {
            "pad": "02D43B2D1103A80D",
            "data": "33A457947EE4A83F"
          },
          "crypto_hash": "7CF4",
          "is_placeholder_selection": false,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "30580730EC6097CC",
            "proof_zero_data": "7F1EB990C2E1DDCC",
            "proof_one_pad": "9CA843BB5BE16B71",
            "proof_one_data": "32E4D9E6F2A208",
            "proof_zero_challenge": "649E",
            "proof_one_challenge": "570C",
            "challenge": "BBAA",
            "proof_zero_response": "E8CA",
            "proof_one_response": "F4D4",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "justice-supreme-court-4-placeholder",
          "sequence_order": 4,
          "description_hash": "2E68",
          "ciphertext": {
            "pad": "C0743BC5CFAEE053",
            "data": "910C06E6651C1644"
          },
          "crypto_hash": "5A72",
          "is_placeholder_selection": true,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "C6A3B2DD00B3EA19",
            "proof_zero_data": "27DAB8EAA831194C",
            "proof_one_pad": "0AFE4F3F5EE436DD",
            "proof_one_data": "57004BE493CEBFE5",
            "proof_zero_challenge": "1709",
            "proof_one_challenge": "7592",
            "challenge": "8C9B",
            "proof_zero_response": "2DDB",
            "proof_one_response": "29E7",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        },
        {
          "object_id": "justice-supreme-court-5-placeholder",
          "sequence_order": 5,
          "description_hash": "5C58",
          "ciphertext": {
            "pad": "17C6E68921D4C5CA",
            "data": "C94BAE8C2A93279D"
          },
          "crypto_hash": "4505",
          "is_placeholder_selection": true,
          "nonce": null,
          "proof": {
            "proof_zero_pad": "D74F6F8A85D06AD1",
            "proof_zero_data": "C720BEAFAB2C014D",
            "proof_one_pad": "D506918F9C176209",
            "proof_one_data": "B91F714CFBFF5CB7",
            "proof_zero_challenge": "6383",
            "proof_one_challenge": "45D8",
            "challenge": "A95B",
            "proof_zero_response": "4EC8",
            "proof_one_response": "8940",
            "usage": "Prove selection's value (0 or 1)"
          },
          "extended_data": null
        }
      ],
      "ciphertext_accumulation": {
        "pad": "603D1615FC21F997",
        "data": "B65826977720E7B8"
      },
      "crypto_hash": "8050",
      "nonce": null,
      "proof": {
        "pad": "AD1C5E6BCC225A45",
        "data": "75BE384577563CEE",
        "challenge": "73CC",
        "response": "180D",
        "constant": 2,
        "usage": "Prove value within selection's limit"
      },
      "extended_data": null
    }
  ],
  "code": "0936",
  "timestamp": 1651598671,
  "crypto_hash": "C880",
  "nonce": null,
  "state": 1
}
