=== Election-Tech-Initiative/electionguard/data/range-proofs/schema/ciphertext_ballot.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://electionguard.vote/schemas/range-proofs/ciphertext-ballot",
  "title": "Ciphertext Ballot",
  "type": "object",
  "required": [
    "object_id",
    "style_id",
    "manifest_hash",
    "code_seed",
    "contests",
    "code",
    "timestamp",
    "crypto_hash",
    "nonce"
  ],
  "definitions": {
    "SequenceOrder": {
      "title": "Sequence Order",
      "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
      "type": "integer",
      "minimum": 1
    },
    "ElementModP": {
      "title": "ElementModP",
      "description": "An element of the larger `mod p` space, i.e., in [0, P), where P is a 4096-bit prime.",
      "type": "string"
    },
    "ElementModQ": {
      "title": "ElementModQ",
      "description": "An element of the smaller `mod q` space, i.e., in [0, Q), where Q is a 256-bit prime.",
      "type": "string"
    },
    "ElGamalCiphertext": {
      "title": "ElGamal Ciphertext",
      "description": "An exponential ElGamal ciphertext",
      "type": "object",
      "required": ["pad", "data"],
      "properties": {
        "pad": {
          "title": "Pad",
          "description": "pad or alpha",
          "$ref": "#/definitions/ElementModQ"
        },
        "data": {
          "title": "Data",
          "description": "encrypted data or beta",
          "$ref": "#/definitions/ElementModQ"
        }
      }
    },
    "HashedElGamalCiphertext": {
      "title": "Hashed ElGamal Ciphertext",
      "description": "A hashed version of ElGamal Ciphertext with less size restrictions.",
      "type": "object",
      "required": ["pad", "data", "mac"],
      "properties": {
        "pad": {
          "title": "Pad",
          "description": "pad or alpha",
          "$ref": "#/definitions/ElementModP"
        },
        "data": {
          "title": "Data",
          "description": "encrypted data or beta",
          "type": "string"
        },
        "mac": {
          "title": "MAC",
          "description": "message authentication code for hmac",
          "type": "string"
        }
      }
    },
    "ProofUsage": {
      "title": "Proof Usage",
      "description": "Usage case for proof",
      "type": "string",
      "enum": [
        "Unknown",
        "Prove knowledge of secret value",
        "Prove value is a given constant",
        "Prove value is within a given range (0, 1, ..., or limit)"
      ],
      "default": "Unknown"
    },
    "RangeChaumPedersenProof": {
      "title": "Range Chaum-Pedersen Proof",
      "description": "Representation of range Chaum-Pederson proof",
      "type": "object",
      "required": [
        "commitments",
        "challenges",
        "responses",
        "limit",
        "usage"
      ],
      "properties": {
        "commitments": {
          "title": "Commitments",
          "description": "List of commitments a0, b0, a1, b1, ..., aL, bL",
          "type": "array",
          "minItems": 4,
          "items": {
            "title": "Items",
            "$ref": "#/definitions/ElementModP"
          }
        },
        "challenges": {
          "title": "Challenges",
          "description": "List of challenges c0, c1, ..., cL, c",
          "type": "array",
          "minItems": 3,
          "items": {
            "title": "Items",
            "$ref": "#/definitions/ElementModQ"
          }
        },
        "responses": {
          "title": "Responses",
          "description": "List of responses v0, v1, ..., vL",
          "type": "array",
          "minItems": 2,
          "items": {
            "title": "Items",
            "$ref": "#/definitions/ElementModQ"
          }
        },
        "limit": {
          "title": "Selection limit",
          "description": "L in the spec",
          "type": "integer"
        },
        "usage": {
          "title": "Usage",
          "description": "A description of how to use this proof",
          "$ref": "#/definitions/ProofUsage",
          "default": "Prove value is within a given range (0, 1, ..., or limit)"
        }
      }
    },
    "CiphertextBallotSelection": {
      "title": "Ciphertext Ballot Selection",
      "description": "A CiphertextBallotSelection represents an individual encrypted selection on a ballot.",
      "type": "object",
      "required": [
        "object_id",
        "sequence_order",
        "description_hash",
        "ciphertext",
        "crypto_hash",
        "nonce",
        "proof",
        "selection_limit"
      ],
      "properties": {
        "object_id": {
          "title": "Object_id",
          "type": "string"
        },
        "sequence_order": {
          "title": "Sequence Order",
          "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
          "$ref": "#/definitions/SequenceOrder"
        },
        "description_hash": {
          "title": "Description_hash",
          "description": "The SelectionDescription hash",
          "$ref": "#/definitions/ElementModQ"
        },
        "ciphertext": {
          "title": "Ciphertext",
          "description": "The encrypted representation of the vote field",
          "$ref": "#/definitions/ElGamalCiphertext"
        },
        "crypto_hash": {
          "title": "Crypto Hash",
          "description": "The hash of the encrypted values",
          "$ref": "#/definitions/ElementModQ"
        },
        "nonce": {
          "title": "Nonce",
          "description": "The nonce used to generate the encryption. Sensitive & should be treated as a secret",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/ElementModQ" }
          ],
          "default": null
        },
        "proof": {
          "title": "Proof",
          "description": "The proof that demonstrates the selection is an encryption of 0, 1, ..., limit, and was encrypted using the `nonce`",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/RangeChaumPedersenProof" }
          ],
          "default": null
        },
        "selection_limit": {
          "title": "Selection Limit",
          "description": "Maximum number of votes allowed for the selection",
          "type": "integer"
        }
      }
    },
    "CiphertextBallotContest": {
      "title": "Ciphertext Ballot Contest",
      "description": "A CiphertextBallotContest represents the selections made by a voter for a specific ContestDescription.",
      "type": "object",
      "required": [
        "object_id",
        "sequence_order",
        "description_hash",
        "ballot_selections",
        "ciphertext_accumulation",
        "crypto_hash",
        "contest_limit",
        "nonce",
        "proof",
        "extended_data"
      ],
      "properties": {
        "object_id": {
          "title": "Object Id",
          "type": "string"
        },
        "sequence_order": {
          "title": "Sequence Order",
          "description": "Used for ordering in a ballot to ensure various encryption primitives are deterministic.",
          "$ref": "#/definitions/SequenceOrder"
        },
        "description_hash": {
          "title": "Description Hash",
          "description": "Hash from contestDescription",
          "$ref": "#/definitions/ElementModQ"
        },
        "ballot_selections": {
          "title": "Ballot_selections",
          "type": "array",
          "minItems": 1,
          "items": {
            "title": "Items",
            "$ref": "#/definitions/CiphertextBallotSelection"
          }
        },
        "ciphertext_accumulation": {
          "title": "Ciphertext Accumulation",
          "description": "The encrypted representation of all of the vote fields (the contest total)",
          "$ref": "#/definitions/ElGamalCiphertext"
        },
        "crypto_hash": {
          "title": "Crypto Hash",
          "description": "Hash of the encrypted values",
          "$ref": "#/definitions/ElementModQ"
        },
        "contest_limit": {
          "title": "Contest Limit",
          "description": "Maximum total number of votes allowed across all selections for the contest",
          "type": "integer"
        },
        "nonce": {
          "title": "Nonce",
          "description": "The nonce used to generate the encryption. Sensitive & should be treated as a secret",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/ElementModQ" }
          ],
          "default": null
        },
        "proof": {
          "title": "Proof",
          "description": "The proof that demonstrates the sum of values encrypted in the selections does not exceed the maximum available for the contest",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/RangeChaumPedersenProof" }
          ],
          "default": null
        },
        "extended_data": {
          "title": "Extended Data",
          "description": "Encrypted representation of the extended_data field",
          "oneOf": [
            { "type": "null" },
            { "$ref": "#/definitions/HashedElGamalCiphertext" }
          ],
          "default": null
        }
      }
    }
  },
  "properties": {
    "object_id": {
      "title": "Object Id",
      "type": "string"
    },
    "style_id": {
      "title": "Style Id",
      "description": "The `object_id` of the `BallotStyle` in the `Election` Manifest",
      "type": "string"
    },
    "manifest_hash": {
      "title": "Manifest Hash",
      "description": "Hash of the election manifest",
      "$ref": "#/definitions/ElementModQ"
    },
    "code_seed": {
      "title": "Code_seed",
      "description": "Seed for ballot code",
      "$ref": "#/definitions/ElementModQ"
    },
    "contests": {
      "title": "Contests",
      "description": "List of contests for this ballot",
      "type": "array",
      "minItems": 1,
      "items": {
        "title": "Items",
        "$ref": "#/definitions/CiphertextBallotContest"
      }
    },
    "code": {
      "title": "Code",
      "description": "Unique ballot code for this ballot",
      "$ref": "#/definitions/ElementModQ"
    },
    "timestamp": {
      "title": "Timestamp",
      "description": "Timestamp at which the ballot encryption is generated in tick",
      "type": "integer"
    },
    "crypto_hash": {
      "title": "Crypto Hash",
      "description": "The hash of the encrypted ballot representation",
      "$ref": "#/definitions/ElementModQ"
    },
    "nonce": {
      "title": "Nonce",
      "description": "The nonce used to encrypt this ballot. Sensitive & should be treated as a secret",
      "oneOf": [{ "type": "null" }, { "$ref": "#/definitions/ElementModQ" }],
      "default": null
    }
  }
}

=== Election-Tech-Initiative/electionguard/data/range-proofs/sample/jefferson-primary/election_private_data/ciphertext_ballots/ciphertext_ballot_25a7111b-4334-425a-87c1-f7a49f42b3a2.json
{
    "object_id": "25a7111b-4334-425a-87c1-f7a49f42b3a2",
    "style_id": "jefferson-county-ballot-style",
    "manifest_hash": "6A75",
    "code_seed": "5418",
    "contests": [
        {
            "object_id": "justice-supreme-court",
            "sequence_order": 1,
            "description_hash": "5E36",
            "ballot_selections": [
                {
                    "object_id": "john-adams-selection",
                    "sequence_order": 1,
                    "description_hash": "04C8",
                    "ciphertext": {
                        "pad": "1A9500462A8D7F79",
                        "data": "1DF98132B7F4E9D6"
                    },
                    "crypto_hash": "C855",
                    "nonce": "C184",
                    "proof": {
                        "commitments": [
                            "5197CE57B12CAFAB",
                            "4C613EB4DA7AABC8",
                            "9EBED2534EBC19E4",
                            "5C73B8A33090DA72"
                        ],
                        "challenges": [
                            "A346",
                            "A15C",
                            "44B1"
                        ],
                        "responses": [
                            "1904",
                            "28FF"
                        ],
                        "limit": 1,
                        "usage": "Prove value is within a given range (0, 1, ..., or limit)"
                    },
                    "selection_limit": 1
                },
                {
                    "object_id": "benjamin-franklin-selection",
                    "sequence_order": 2,
                    "description_hash": "84DC",
                    "ciphertext": {
                        "pad": "D69A737168017939",
                        "data": "F0D68DAF372D6BAB"
                    },
                    "crypto_hash": "AA19",
                    "nonce": "BB",
                    "proof": {
                        "commitments": [
                            "4DB6926EB5BEC47C",
                            "43EB066BDCB960C1",
                            "9BC073C186380543",
                            "2A690352CAB96B75"
                        ],
                        "challenges": [
                            "D83A",
                            "BCC1",
                            "950A"
                        ],
                        "responses": [
                            "710B",
                            "15EB"
                        ],
                        "limit": 1,
                        "usage": "Prove value is within a given range (0, 1, ..., or limit)"
                    },
                    "selection_limit": 1
                },
                {
                    "object_id": "john-hancock-selection",
                    "sequence_order": 3,
                    "description_hash": "663D",
                    "ciphertext": {
                        "pad": "471717E5E5D00D01",
                        "data": "2FB0ACD6FD9C9579"
                    },
                    "crypto_hash": "C8B4",
                    "nonce": "72E7",
                    "proof": {
                        "commitments": [
                            "4ACB700A11B65DAE",
                            "28D3A86130E6C22F",
                            "CE885A2F13FCADC3",
                            "CFD2791BF4B97109"
                        ],
                        "challenges": [
                            "A830",
                            "6292",
                            "0AD1"
                        ],
                        "responses": [
                            "75CD",
                            "4016"
                        ],
                        "limit": 1,
                        "usage": "Prove value is within a given range (0, 1, ..., or limit)"
                    },
                    "selection_limit": 1
                },
                {
                    "object_id": "write-in-selection",
                    "sequence_order": 4,
                    "description_hash": "4B6E",
                    "ciphertext": {
                        "pad": "2654D83F7A2C276D",
                        "data": "962E88A421C1B6EC"
                    },
                    "crypto_hash": "191A",
                    "nonce": "14CA",
                    "proof": {
                        "commitments": [
                            "35410DF01B5A88CB",
                            "63C7C0CD57AB728A",
                            "89CE188AA4FC13F2",
                            "CAE3DDE8800AB865"
                        ],
                        "challenges": [
                            "AC86",
                            "4206",
                            "EE8C"
                        ],
                        "responses": [
                            "3A81",
                            "35A2"
                        ],
                        "limit": 1,
                        "usage": "Prove value is within a given range (0, 1, ..., or limit)"
                    },
                    "selection_limit": 1
                }
            ],
            "ciphertext_accumulation": {
                "pad": "E05A155828E85231",
                "data": "1FEC79D42B4EBB09"
            },
            "crypto_hash": "0D80",
            "contest_limit": 2,
            "nonce": "6F54",
            "proof": {
                "commitments": [
                    "9DF1E45B081EFAEF",
                    "CF39E4287409030C",
                    "7F15520182FA7B6C",
                    "DEF370702E0EE550",
                    "EAE8F1358CCB1CF8",
                    "9BC43BF67C2006BA"
                ],
                "challenges": [
                    "8A63",
                    "D4D9",
                    "A3ED",
                    "0347"
                ],
                "responses": [
                    "65F3",
                    "B0A7",
                    "5476"
                ],
                "limit": 2,
                "usage": "Prove value is within a given range (0, 1, ..., or limit)"
            },
            "extended_data": {
                "pad": "79088301C2059AC4",
                "data": "BFE383D964F93AE18C6E2E8F22B5F3EF9D9E4B46E140DB23A0E531B7CC8FCFB9494B729A39122CB3DF829DE29227BA25BE11570D0D2EAE10270E931CA8150E70DC49617605289DEBB82693F102AFBE66BEE84E8E0C2B0BEFD401F9FB37633ECEBFB7A7410C61F94136E9FCE2885C89DF06FCBBB3076F64E792BC4B53FFCA0744423BFCE17954FBE3720FFBF0C61F1E290F5448458364E05E60C8D6C073489B2E9CFC337C7CC7EE400E86E3A33B22F2FB0F432A17E09DC28EF7309767BCC7F3760190EF4D23E02BA9F55398494C73E5A4FC6600D62C78547F87E95C8279316B2717664FAD9284E031E9C69A36DD8A742A3782D4C91551812BF128C00DD9300336176D825062D28BA06FEC49E5C8E78A8E2B0927FDC81121A799F61C8E5E4B22E0567F343872980EA0951E0245FB8F658D973B4A1C42ACAFED130A79FD9CA9A8245F7EB530CDC8C5214E866BE86E0CF7993AE6D12E7279CCD8949085153A3585D292CD1DD658518EFA5DD5D906771AA329E882022C5A3EE6A355CBF8B07E1125EA8F1460A362498741BF051F93D3CBB0249E1BF16B808318E70A67CFFC0A338EA30F4A0AE0A82A6EF920451D4F4E3697B73083A0436D173EFC5D35D69FAAE1FBF6E4389E0FBBB097F31ABC6A11F4AA5654915E638751E221929D44E18342D9EB05BAA9198062FFACDF80F050C4AFA995CDCC2A7CFC94C67CE08C73D0DF333894A1",
                "mac": "1D897121FEDF678F098D9F9C92AA1A1EE1119DC36EE1E663C5F03DB8FC03950C"
            }
        }
    ],
    "code": "3F87",
    "timestamp": 1660841182,
    "crypto_hash": "0302",
    "nonce": "CD4F"
}
