=== Election-Tech-Initiative/electionguard/data/1.91/schema/ciphertext_election_context.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://electionguard.vote/schemas/1.91/election-context",
  "title": "Ciphertext Election Context",
  "type": "object",
  "required": [
    "number_of_guardians",
    "quorum",
    "elgamal_public_key",
    "commitment_hash",
    "manifest_hash",
    "crypto_base_hash",
    "crypto_extended_base_hash",
    "configuration"
  ],
  "definitions": {
    "ElementModP": {
      "title": "ElementModP",
      "description": "An element of the larger `mod p` space, i.e., in [0, P), where P is a 4096-bit prime.",
      "type": "string"
    },
    "ElementModQ": {
      "title": "ElementModQ",
      "description": "An element of the smaller `mod q` space, i.e., in [0, Q), where Q is a 256-bit prime.",
      "type": "string"
    },
    "Configuration": {
      "title": "Configuration",
      "type": "object",
      "properties": {
        "allow_overvotes": {
          "title": "Allow Overvotes",
          "default": true,
          "type": "boolean"
        },
        "max_votes": {
          "title": "Max Votes",
          "default": 1000000,
          "type": "integer"
        }
      }
    }
  },
  "properties": {
    "number_of_guardians": {
      "title": "Number Of Guardians",
      "type": "integer",
      "description": "The number of guardians necessary to generate the public key"
    },
    "quorum": {
      "title": "Quorum",
      "type": "integer",
      "description": "The quorum of guardians necessary to decrypt an election.  Must be less than or equal to `number_of_guardians`"
    },
    "elgamal_public_key": {
      "$ref": "#/definitions/ElementModP",
      "description": "The `joint public key (K)` in the specification"
    },
    "commitment_hash": {
      "$ref": "#/definitions/ElementModQ",
      "description": "the `commitment hash H(K 1,0 , K 2,0 ... , K n,0 )` of the public commitments guardians make to each other in the specification"
    },
    "manifest_hash": {
      "$ref": "#/definitions/ElementModQ",
      "description": "The hash of the election metadata"
    },
    "crypto_base_hash": {
      "$ref": "#/definitions/ElementModQ",
      "description": "The `base hash code (ùëÑ)` in the specification"
    },
    "crypto_extended_base_hash": {
      "$ref": "#/definitions/ElementModQ",
      "description": "The `extended base hash code (ùëÑ')` in specification"
    },
    "extended_data": {
      "title": "Extended Data",
      "type": ["object", "null"],
      "description": "Data to allow extending the context for special cases",
      "additionalProperties": {
        "type": "string"
      }
    },
    "configuration": {
      "$ref": "#/definitions/Configuration",
      "description": "Configuration for the election edge cases"
    }
  }
}

=== Election-Tech-Initiative/electionguard/data/1.91/sample/context.json
{"commitment_hash":"648332C6CCABA6E42D910FD81D6A60471E6FB30E127F0AA7A143B93C4499EC3F","configuration":{"allow_overvotes":true,"max_votes":1000000},"crypto_base_hash":"97F22B9EF2542C27EF5E9C2C8B3B0D38586E011FA695F8F1084666BEF2326F3F","crypto_extended_base_hash":"B4A066C63BB36217F79D18AE610B364B3A7D8935E293488364D9EE3058184947","elgamal_public_key":"59587D05938E9F38226FAD38EE257B309677D75D0BDE3BDFF6F5EF8B425926CCEE3D6FE40FF7528531CC9E4E80B11421355DC78B8A2E8C7C7116D96A681340D8459BAB96E919D0CE0ED6BF6D99C705871DF5EACFA9067E0E258496DE04281C5D887AFCE9FC689649AB6190A5B22D7EC3850B4D0823F08AE4148827434D1EC1AE28CC1F20E0E59C2EDA3453EA8EE6B1D17A41E9B7E88C6B15D1501AE10E030F35C15683454413393C39B7795C69907EB84F6C10A50A868F0D083D1800218595746EECCDB7696C115AFD80B86B32502F68BCECD65963FFB21F478358DBF0CB41FAF6DA8EDDC4FBBAFF6EFFD6AB19896CD0F5C1B97A7EFAEAFABF87729F936899279135FCA91D8BB58A8845FAFEBA7F70EA818C06A4794C5297E95B7BA3E1D3DB967487D8BB40AE57256918B73594977B8D462071FFFF07A5A0126B4FB8E7A4F294B273621F9D4EB2722A651837F89B32B9E08A94149A3331F4B6823F8DFDB528161CF40CC20C6C84B01147CC12F490D964AD157D668AA30B1B446A153912545FA4824B6A5C813C90FBB0D1F016C1AE19E1D73F0CDC654A98F8C1432B693D189BB7FDAC7528B8C767EBD6D4DEA3CE0BD2FF97CAFBCC4DB60C561837BD49694A83C9760A3DBD9B027C70CFBB3A48F01B621696578619FF660C14E4DF69DAD2DC94CE816AE8F5C13EF501390B490440739CEAAF3787F8F1EB23697C71193673E3469D","extended_data":{"verification_url":"http://electionguard.vote/jefferson"},"manifest_hash":"33A2F06E743408F44DDDC5C9DDA0FCBA867A981C8340ECC272C02D19F4BC6BF5","number_of_guardians":3,"quorum":2}
